# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(591, 235)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(10, 10, 571, 221))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.save = QtWidgets.QPushButton(parent=self.widget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 6, 1, 1, 1)
        self.work = QtWidgets.QCheckBox(parent=self.widget)
        self.work.setObjectName("work")
        self.gridLayout.addWidget(self.work, 5, 0, 1, 1)
        self.savetofile = QtWidgets.QPushButton(parent=self.widget)
        self.savetofile.setObjectName("savetofile")
        self.gridLayout.addWidget(self.savetofile, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.listWidget = QtWidgets.QListWidget(parent=self.widget)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 6, 0, 1, 1)
        self.name = QtWidgets.QLineEdit(parent=self.widget)
        self.name.setObjectName("name")
        self.gridLayout.addWidget(self.name, 0, 1, 1, 1)
        self.surname = QtWidgets.QLineEdit(parent=self.widget)
        self.surname.setObjectName("surname")
        self.gridLayout.addWidget(self.surname, 1, 1, 1, 1)
        self.phone = QtWidgets.QLineEdit(parent=self.widget)
        self.phone.setObjectName("phone")
        self.gridLayout.addWidget(self.phone, 3, 1, 1, 1)
        self.pesel = QtWidgets.QLineEdit(parent=self.widget)
        self.pesel.setObjectName("pesel")
        self.gridLayout.addWidget(self.pesel, 4, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.save.setText(_translate("Dialog", "zapisz"))
        self.work.setText(_translate("Dialog", "Umowa o prace"))
        self.savetofile.setText(_translate("Dialog", "zapisz do pliku"))
        self.label_3.setText(_translate("Dialog", "numer telefonu"))
        self.label.setText(_translate("Dialog", "Imie"))
        self.label_2.setText(_translate("Dialog", "Nazwisko"))
        self.label_4.setText(_translate("Dialog", "PESEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
